spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mixtech
    username: public
    password: public123456
  security:
    oauth2:
      client:
        registration:
          spotify:
            clientId: ae1c25b01ed94b4cb0b48cd1e679f051
            clientSecret: 8a9d601440204112b46c1d3e4d0d26e4
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user-read-email
              - user-read-private
              - playlist-read-collaborative
              - playlist-modify-public
              - playlist-read-private
              - playlist-modify-private
              - user-modify-playback-state
              - user-read-playback-state
              - user-read-currently-playing
              - streaming
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: email

server:
  servlet:
    context-path: /api

app-security:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMilliSec: 3600000
  frontendRedirectUri: http://localhost:3000/oauth2/redirect